name: '[Support] Synchronize labels from the vms repository'
on:
  schedule:
    # Daily
    - cron: '0 3 * * *'
permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          source-repo: bitnami/vms
          delete-other-labels: false
          token: ${{ secrets.GITHUB_TOKEN }}